
---- Montly Trx table summarized basd on CARD_ACCOUNT_UNIQUE_ID and BILLING_DATE
WITH TRAX_TABLE AS (
SELECT CCI.CARD_ACCOUNT_NUMBER
,ST.BILLING_DATE
--,ROUND(MONTHS_BETWEEN('2024-01-20',DATE(BILLING_DATE)),0) AS diff_month
--,MONTHS_BETWEEN('2024-01-20',DATE(BILLING_DATE)) AS diff_month_
--,CAST(MONTHS_BETWEEN('2024-01-20',DATE(BILLING_DATE)) AS INT) AS diff_month_1
,ROUND(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)),0) AS diff_month
,MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)) AS diff_month_
,CAST(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)) AS INT) AS diff_month_1
,SUM(ST.CARD_OUTSTANDING_BALANCE) AS CARD_OUTSTANDING_BALANCE
,SUM(ST.MTD_PURCHASE_AMOUNT + ST.MTD_CASH_ADVANCE_AMOUNT+ ST.MTD_FEES_AMOUNT +ST.FINANCIAL_CHARGES) AS TOTAL_PURCHASE
,SUM(ST.MTD_PAYMENT_AMOUNT+ ST.MTD_RETURN_AMOUNT) AS TOTAL_PAYMENTS
FROM SBPRDNDTA.DSCS031D CCI -- credit card info table
JOIN SBPRDNDTA.DSCS151F ST ---Bill history TABLE
ON CCI.CARD_ACCOUNT_UNIQUE_ID  = ST.CARD_ACCOUNT_UNIQUE_ID
WHERE CCI.CARD_ACCOUNT_STATUS NOT IN('RP','CL')
AND CCI.CREDIT_LIMIT_ADJUSTMENT_AMOUNT > 0
AND MONTHS_BETWEEN(CURRENT_DATE, ST.BILLING_DATE) <= 26
--AND DAY(ST.BILLING_DATE)>=15
--AND CAST(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)) AS INT)=0
--AND ROUND(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)),0) <> 1
--AND CCI.CARD_ACCOUNT_NUMBER = 'C000000000000154016'
GROUP BY CCI.CARD_ACCOUNT_NUMBER,ST.BILLING_DATE
ORDER BY ST.BILLING_DATE DESC  
)

--SUMARIZED AS (
--SELECT CARD_ACCOUNT_NUMBER
--,BILLING_DATE
--,diff_month_1
--,CARD_OUTSTANDING_BALANCE
--,TOTAL_PURCHASE
--,TOTAL_PAYMENTS
--FROM TRAX_TABLE
--
--)

SELECT TX.CARD_ACCOUNT_NUMBER
--,TX.diff_month_1
--,TX.CARD_OUTSTANDING_BALANCE
--,TX.TOTAL_PURCHASE
--,TX.TOTAL_PAYMENTS
,SUM(CASE WHEN diff_month_1=0 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_0
,SUM(CASE WHEN diff_month_1=1 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_1
,SUM(CASE WHEN diff_month_1=2 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_2
,SUM(CASE WHEN diff_month_1=3 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_3
,SUM(CASE WHEN diff_month_1=4 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_4
,SUM(CASE WHEN diff_month_1=5 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_5
,SUM(CASE WHEN diff_month_1=6 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_6
,SUM(CASE WHEN diff_month_1=7 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_7
,SUM(CASE WHEN diff_month_1=8 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_8
,SUM(CASE WHEN diff_month_1=9 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_9
,SUM(CASE WHEN diff_month_1=10 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_10
,SUM(CASE WHEN diff_month_1=11 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_11
,SUM(CASE WHEN diff_month_1=12 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_12
,SUM(CASE WHEN diff_month_1=13 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_13
,SUM(CASE WHEN diff_month_1=14 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_14
,SUM(CASE WHEN diff_month_1=15 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_15
,SUM(CASE WHEN diff_month_1=16 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_16
,SUM(CASE WHEN diff_month_1=17 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_17
,SUM(CASE WHEN diff_month_1=18 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_18
,SUM(CASE WHEN diff_month_1=19 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_19
,SUM(CASE WHEN diff_month_1=20 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_20
,SUM(CASE WHEN diff_month_1=21 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_21
,SUM(CASE WHEN diff_month_1=22 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_22
,SUM(CASE WHEN diff_month_1=23 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_23
,SUM(CASE WHEN diff_month_1=24 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_24
,SUM(CASE WHEN diff_month_1=25 THEN TX.CARD_OUTSTANDING_BALANCE END) AS TOT_OUTSTAND_BAL_25

,SUM(CASE WHEN diff_month_1=0 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_0
,SUM(CASE WHEN diff_month_1=1 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_1
,SUM(CASE WHEN diff_month_1=2 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_2
,SUM(CASE WHEN diff_month_1=3 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_3
,SUM(CASE WHEN diff_month_1=4 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_4
,SUM(CASE WHEN diff_month_1=5 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_5
,SUM(CASE WHEN diff_month_1=6 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_6
,SUM(CASE WHEN diff_month_1=7 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_7
,SUM(CASE WHEN diff_month_1=8 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_8
,SUM(CASE WHEN diff_month_1=9 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_9
,SUM(CASE WHEN diff_month_1=10 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_10
,SUM(CASE WHEN diff_month_1=11 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_11
,SUM(CASE WHEN diff_month_1=12 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_12
,SUM(CASE WHEN diff_month_1=13 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_13
,SUM(CASE WHEN diff_month_1=14 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_14
,SUM(CASE WHEN diff_month_1=15 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_15
,SUM(CASE WHEN diff_month_1=16 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_16
,SUM(CASE WHEN diff_month_1=17 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_17
,SUM(CASE WHEN diff_month_1=18 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_18
,SUM(CASE WHEN diff_month_1=19 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_19
,SUM(CASE WHEN diff_month_1=20 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_20
,SUM(CASE WHEN diff_month_1=21 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_21
,SUM(CASE WHEN diff_month_1=22 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_22
,SUM(CASE WHEN diff_month_1=23 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_23
,SUM(CASE WHEN diff_month_1=24 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_24
,SUM(CASE WHEN diff_month_1=25 THEN TX.TOTAL_PURCHASE END) AS TOTAL_PURCHASE_25

,SUM(CASE WHEN diff_month_1=0 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_0
,SUM(CASE WHEN diff_month_1=1 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_1
,SUM(CASE WHEN diff_month_1=2 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_2
,SUM(CASE WHEN diff_month_1=3 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_3
,SUM(CASE WHEN diff_month_1=4 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_4
,SUM(CASE WHEN diff_month_1=5 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_5
,SUM(CASE WHEN diff_month_1=6 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_6
,SUM(CASE WHEN diff_month_1=7 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_7
,SUM(CASE WHEN diff_month_1=8 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_8
,SUM(CASE WHEN diff_month_1=9 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_9
,SUM(CASE WHEN diff_month_1=10 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_10
,SUM(CASE WHEN diff_month_1=11 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_11
,SUM(CASE WHEN diff_month_1=12 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_12
,SUM(CASE WHEN diff_month_1=13 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_13
,SUM(CASE WHEN diff_month_1=14 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_14
,SUM(CASE WHEN diff_month_1=15 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_15
,SUM(CASE WHEN diff_month_1=16 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_16
,SUM(CASE WHEN diff_month_1=17 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_17
,SUM(CASE WHEN diff_month_1=18 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_18
,SUM(CASE WHEN diff_month_1=19 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_19
,SUM(CASE WHEN diff_month_1=20 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_20
,SUM(CASE WHEN diff_month_1=21 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_21
,SUM(CASE WHEN diff_month_1=22 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_22
,SUM(CASE WHEN diff_month_1=23 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_23
,SUM(CASE WHEN diff_month_1=24 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_24
,SUM(CASE WHEN diff_month_1=25 THEN TX.TOTAL_PAYMENTS END) AS TOTAL_PAYMENTS_25
FROM TRAX_TABLE TX
GROUP BY TX.CARD_ACCOUNT_NUMBER















