--WITH CREDIT_CX AS (
--SELECT CX.CUSTOMER_UNIQUE_ID
--,CCI.CARD_ACCOUNT_UNIQUE_ID
--,CCI.CITIZEN_ID
--,CCI.CREDIT_LIMIT_ADJUSTMENT_AMOUNT
----,CCI.CARD_ACCOUNT_STATUS
--,CCI.ACCOUNT_OPEN_DATE
--,CCI.CARD_ACCOUNT_NUMBER
--,CX.DATE_OF_BIRTH
--,CX.CUSTOMER_GENDER
--,CX.OCCUPATION_CODE
--,CX.OCCUPATION
--,CX.CUSTOMER_JOB
--,CX.MONTHLY_INCOME
--,CX.MARITIAL_STATUS
--FROM SBPRDNDTA.DSCU001D CX
--INNER JOIN (SELECT DISTINCT CUSTOMER_UNIQUE_ID, CARD_ACCOUNT_UNIQUE_ID
--			FROM SBPRDNDTA.DSCS150F 
--			) AS CCWB ON CCWB.CUSTOMER_UNIQUE_ID = CX.CUSTOMER_UNIQUE_ID
--INNER JOIN (SELECT DISTINCT CARD_ACCOUNT_UNIQUE_ID,CITIZEN_ID,CREDIT_LIMIT_ADJUSTMENT_AMOUNT,CARD_ACCOUNT_STATUS,CARD_ACCOUNT_NUMBER
--					,(CASE WHEN ACCOUNT_OPEN_DATE = '0001-01-01' THEN EXTRA_DATE_2 ELSE ACCOUNT_OPEN_DATE END) AS ACCOUNT_OPEN_DATE
--			FROM SBPRDNDTA.DSCS031D  -- credit card information table
--			--WHERE EFFECTIVE_TO_DATE='9999-12-31' AND 
--			WHERE CARD_ACCOUNT_STATUS NOT IN('RP','CL')
--			AND CREDIT_LIMIT_ADJUSTMENT_AMOUNT > 0
--			AND (REGEXP_LIKE(VIP_PROFILE,TRIM('^[Cc][Aa][Ss][Hh]\s*[Bb][Aa][Cc][Kk]')) OR REGEXP_LIKE(VIP_PROFILE,TRIM('^[Ss][Vv][Ii]')))
--			) AS CCI ON CCI.CARD_ACCOUNT_UNIQUE_ID = CCWB.CARD_ACCOUNT_UNIQUE_ID
--UNION ALL 
--SELECT CX.CUSTOMER_UNIQUE_ID
--,CCI.CARD_ACCOUNT_UNIQUE_ID
--,CCI.CITIZEN_ID
--,CCI.CREDIT_LIMIT_ADJUSTMENT_AMOUNT
----,CCI.CARD_ACCOUNT_STATUS
--,CCI.ACCOUNT_OPEN_DATE
--,CCI.CARD_ACCOUNT_NUMBER
--,CX.DATE_OF_BIRTH
--,CX.CUSTOMER_GENDER
--,CX.OCCUPATION_CODE
--,CX.OCCUPATION
--,CX.CUSTOMER_JOB
--,CX.MONTHLY_INCOME
--,CX.MARITIAL_STATUS
--FROM SBPRDNDTA.DSCU001D CX
--INNER JOIN (SELECT DISTINCT CUSTOMER_UNIQUE_ID, CARD_ACCOUNT_UNIQUE_ID
--			FROM SBPRDNDTA.DSCS150F 
--			) AS CCWB ON CCWB.CUSTOMER_UNIQUE_ID = CX.CUSTOMER_UNIQUE_ID
--INNER JOIN (SELECT DISTINCT CARD_ACCOUNT_UNIQUE_ID,CITIZEN_ID,CREDIT_LIMIT_ADJUSTMENT_AMOUNT,CARD_ACCOUNT_STATUS,CARD_ACCOUNT_NUMBER,ACCOUNT_OPEN_DATE
--			FROM SBPRDNDTA.DSCS031D  -- credit card information table
--			--WHERE EFFECTIVE_TO_DATE='9999-12-31' AND 
--			WHERE CARD_ACCOUNT_STATUS NOT IN('RP','CL')
--			AND CREDIT_LIMIT_ADJUSTMENT_AMOUNT > 0
--			AND NOT (REGEXP_LIKE(VIP_PROFILE,TRIM('^[Cc][Aa][Ss][Hh]\s*[Bb][Aa][Cc][Kk]')) OR REGEXP_LIKE(VIP_PROFILE,TRIM('^[Ss][Vv][Ii]')))
--			) AS CCI ON CCI.CARD_ACCOUNT_UNIQUE_ID = CCWB.CARD_ACCOUNT_UNIQUE_ID
--
--)

--SELECT *--count(DISTINCT CARD_ACCOUNT_UNIQUE_ID)  --101538
--FROM CREDIT_CX
--WHERE CARD_ACCOUNT_NUMBER = 'C000000000000001088'
----WHERE CARD_ACCOUNT_NUMBER = 'C000000000000240046'--'C000000000000240046'



WITH CREDIT_CX AS (
SELECT 
CCI.CARD_ACCOUNT_NUMBER
,CCI.CARD_ACCOUNT_UNIQUE_ID
,CCI.CITIZEN_ID
,CCI.CREDIT_LIMIT_ADJUSTMENT_AMOUNT
,CCI.CARD_ACCOUNT_STATUS
,(CASE WHEN CCI.ACCOUNT_OPEN_DATE = '0001-01-01' THEN CCI.EXTRA_DATE_2 ELSE CCI.ACCOUNT_OPEN_DATE END) AS ACCOUNT_OPEN_DATE
,CCI.VIP_PROFILE
,CX.DATE_OF_BIRTH
,CX.CUSTOMER_GENDER
,CX.OCCUPATION
,CX.MONTHLY_INCOME
FROM SBPRDNDTA.DSCS031D CCI ---Credit card information
LEFT JOIN (SELECT DISTINCT CUSTOMER_UNIQUE_ID, CARD_ACCOUNT_UNIQUE_ID
			FROM SBPRDNDTA.DSCS150F --- cxwithdrawal_balance_table
			) AS CCWB ON CCWB.CARD_ACCOUNT_UNIQUE_ID = CCI.CARD_ACCOUNT_UNIQUE_ID
LEFT JOIN (SELECT DISTINCT CUSTOMER_UNIQUE_ID,DATE_OF_BIRTH,CUSTOMER_GENDER,OCCUPATION,MONTHLY_INCOME
			FROM SBPRDNDTA.DSCU001D  ---- customer infromation table
			) AS CX ON CX.CUSTOMER_UNIQUE_ID = CCWB.CUSTOMER_UNIQUE_ID
WHERE CCI.CARD_ACCOUNT_STATUS NOT IN('RP','CL')
AND CCI.CREDIT_LIMIT_ADJUSTMENT_AMOUNT > 0
AND (REGEXP_LIKE(CCI.VIP_PROFILE,TRIM('^[Cc][Aa][Ss][Hh]\s*[Bb][Aa][Cc][Kk]')) 
		OR REGEXP_LIKE(CCI.VIP_PROFILE,TRIM('^[Ss][Vv][Ii]')))
AND CCI.EFFECTIVE_TO_DATE='9999-12-31'
--AND CCI.CARD_ACCOUNT_NUMBER = 'C000000000000001088'
UNION 
SELECT 
CC.CARD_ACCOUNT_NUMBER
,CC.CARD_ACCOUNT_UNIQUE_ID
,CC.CITIZEN_ID
,CC.CREDIT_LIMIT_ADJUSTMENT_AMOUNT
,CC.CARD_ACCOUNT_STATUS
,CC.ACCOUNT_OPEN_DATE
,CC.VIP_PROFILE
,CX_.DATE_OF_BIRTH
,CX_.CUSTOMER_GENDER
,CX_.OCCUPATION
,CX_.MONTHLY_INCOME
FROM SBPRDNDTA.DSCS031D CC ---credit card information table
LEFT JOIN (SELECT DISTINCT CUSTOMER_UNIQUE_ID, CARD_ACCOUNT_UNIQUE_ID
			FROM SBPRDNDTA.DSCS150F --- cxwithdrawal_balance_table
			) AS CCWB_ ON CCWB_.CARD_ACCOUNT_UNIQUE_ID = CC.CARD_ACCOUNT_UNIQUE_ID
LEFT JOIN (SELECT DISTINCT CUSTOMER_UNIQUE_ID,DATE_OF_BIRTH,CUSTOMER_GENDER,OCCUPATION,MONTHLY_INCOME
			FROM SBPRDNDTA.DSCU001D  ---- customer infromation table
			) AS CX_ ON CX_.CUSTOMER_UNIQUE_ID = CCWB_.CUSTOMER_UNIQUE_ID
WHERE CC.CARD_ACCOUNT_STATUS NOT IN('RP','CL')
AND CC.CREDIT_LIMIT_ADJUSTMENT_AMOUNT > 0
AND NOT(REGEXP_LIKE(CC.VIP_PROFILE,TRIM('^[Cc][Aa][Ss][Hh]\s*[Bb][Aa][Cc][Kk]')) 
		OR REGEXP_LIKE(CC.VIP_PROFILE,TRIM('^[Ss][Vv][Ii]')))
AND CC.EFFECTIVE_TO_DATE='9999-12-31'
--AND CC.CARD_ACCOUNT_NUMBER = 'C000000000000001088'
)


SELECT *
FROM CREDIT_CX
--WHERE CARD_ACCOUNT_NUMBER = 'C000000000000356248' --'C000000000000001088'
--AND EFFECTIVE_TO_DATE='9999-12-31'
