SELECT CCI.CARD_ACCOUNT_NUMBER
,ST.BILLING_DATE
,ST.CARD_ACCOUNT_STATUS
,ROUND(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)),0) AS diff_month
,MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)) AS diff_month_
,CAST(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)) AS INT) AS diff_month_1
FROM SBPRDNDTA.DSCS031D CCI -- credit card info table
JOIN SBPRDNDTA.DSCS151F ST ---Bill history TABLE
ON CCI.CARD_ACCOUNT_UNIQUE_ID  = ST.CARD_ACCOUNT_UNIQUE_ID
WHERE CCI.CARD_ACCOUNT_STATUS NOT IN('RP','CL')
AND CCI.CREDIT_LIMIT_ADJUSTMENT_AMOUNT > 0
AND MONTHS_BETWEEN(CURRENT_DATE, ST.BILLING_DATE) <= 30
--AND CAST(MONTHS_BETWEEN(CURRENT_DATE,DATE(BILLING_DATE)) AS INT) = 0

--AND CCI.CARD_ACCOUNT_NUMBER = 'C000000000000329930'




